// webpack-react/src/App.jsx
// import React from "react";
import "./App.css";
import logo from "./logo.png";

const App = () => {
  return (
    <div>
      <div className="title">hello world</div>
      <img src={logo} className="img" />
      <img src={require("./logo.png")} className="img" />
      <div className="logo"></div>
    </div>
  );
};

export default App;

// webpack-vue/src/App.vue
<template>
  <div class="title">使用webpack搭建vue3脚手架</div>
  <img src="../assets/logo.png" alt="logo" />
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "",

  setup() {},
});
</script>

<style scoped lang="css">
.title {
  color: red;
}
</style>
